### ISSUE TITLE
girder build fails on fresh installation on Macos

### ISSUE THREAD

**Issue by zachmullen** [DigitalSlideArchive/HistomicsUI#266]
Following README instructions for installation, the `girder build` step fails:

```
$ girder build
npm WARN deprecated source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
npm WARN deprecated source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
npm WARN deprecated acorn-dynamic-import@2.0.2: This is probably built in to whatever tool you're using. If you still need it... idk
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
npm WARN deprecated flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
npm WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0
npm WARN deprecated extract-text-webpack-plugin@2.1.2: Deprecated. Please use https://github.com/webpack-contrib/mini-css-extract-plugin
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated svgo@0.7.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated querystring@0.2.0: The querystring API is considered Legacy. new code should use the URLSearchParams API instead.
npm WARN deprecated swagger-ui@2.2.10: No longer maintained, please upgrade to swagger-ui@3.
npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.

added 886 packages, and audited 894 packages in 23s

29 packages are looking for funding
  run `npm fund` for details

73 vulnerabilities (5 low, 43 moderate, 22 high, 3 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

> build
> grunt "--girder-version=3.1.16" "--static-path=/Users/zach/.virtualenvs/histomics/share/girder/static" "--static-public-path=/static" "--no-progress=false" "--env=prod"

Loading "build.js" tasks...ERROR
>> Error: Cannot find module 'webpack'
>> Require stack:
>> - /Users/zach/.virtualenvs/histomics/lib/python3.10/site-packages/girder_large_image/web_client/webpack.helper.js
>> - /Users/zach/.virtualenvs/histomics/lib/python3.10/site-packages/girder/web_client/grunt_tasks/build.js
>> - /Users/zach/.virtualenvs/histomics/lib/python3.10/site-packages/girder/web_client/node_modules/grunt/lib/grunt/task.js
>> - /Users/zach/.virtualenvs/histomics/lib/python3.10/site-packages/girder/web_client/node_modules/grunt/lib/grunt.js
>> - /Users/zach/.virtualenvs/histomics/lib/python3.10/site-packages/girder/web_client/node_modules/grunt-cli/bin/grunt
>> - /Users/zach/.virtualenvs/histomics/lib/python3.10/site-packages/girder/web_client/node_modules/grunt/bin/grunt
Warning: Task "build" not found. Use --force to continue.

Aborted due to warnings.
Traceback (most recent call last):
  File "/Users/zach/.virtualenvs/histomics/bin/girder", line 8, in <module>
    sys.exit(main())
  File "/Users/zach/.virtualenvs/histomics/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/zach/.virtualenvs/histomics/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/zach/.virtualenvs/histomics/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/zach/.virtualenvs/histomics/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/zach/.virtualenvs/histomics/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/zach/.virtualenvs/histomics/lib/python3.10/site-packages/girder/cli/build.py", line 104, in main
    check_call(buildCommand, cwd=staging)
  File "/Users/zach/.pyenv/versions/3.10.4/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['npm', 'run', 'build', '--', '--girder-version=3.1.16', '--static-path=/Users/zach/.virtualenvs/histomics/share/girder/static', '--static-public-path=/static', '--no-progress=false', '--env=prod']' returned non-zero exit status 3.
```

Platform: MacOS v13, M1 (ARM)
Node version: 16.13.0
npm version: 8.1.0
Python version: 3.10.4

**Comment by zachmullen** [comment]
Yikes, they don't even have builds for M1 macs for node@12... need to see what I can do.
