### ISSUE TITLE
Facing Issues with Girder Build Setup

### ISSUE THREAD

**Issue by digs1998** [DigitalSlideArchive/HistomicsUI#363]
I am facing issues when I am trying to install histomics UI in the Linux terminal, it primarily comes when I am running the `girder build` command, the error is below, how do I resolve this? I have updated webpack-dev-server to the latest version still it says it should be at least 2.4.0. 

38 packages are looking for funding
  run `npm fund` for details

72 vulnerabilities (5 low, 42 moderate, 25 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

> build
> grunt "--girder-version=3.1.24" "--static-path=/usr/share/girder/static" "--static-public-path=/static" "--no-progress=false" "--env=dev"

Fatal error: webpack-dev-server is outdated. Please ensure you have at least version 2.4.0 installed.
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/girder", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/girder/cli/build.py", line 104, in main
    check_call(buildCommand, cwd=staging)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['npm', 'run', 'build', '--', '--girder-version=3.1.24', '--static-path=/usr/share/girder/static', '--static-public-path=/static', '--no-progress=false', '--env=dev']' returned non-zero exit status 1.

**Comment by manthey** [comment]
Until we finish a refactor of the girder client build, it currently requires node 14.  If you still have an issue when using node 14, please reopen the issue.
