### ISSUE TITLE
Getting EACCES: permission denied error 

### ISSUE THREAD

**Issue by digs1998** [DigitalSlideArchive/HistomicsUI#364]
I am facing the EACCES error while running the girder build, after following the steps from the repo regarding the installation of Histomics UI on the Linux platform.

Run `npm audit` for details.

> build
> grunt --girder-version=3.1.24 --static-path=/usr/share/girder/static --static-public-path=/static --no-progress=false --env=prod

Running "webpack:core_lib" (webpack) task
 94% asset optimizationWarning: EACCES: permission denied, open '/usr/share/girder/static/built/girder_lib-manifest.json' Use --force to continue.

How do I fix this?

Aborted due to warnings.
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/girder", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/girder/cli/build.py", line 104, in main
    check_call(buildCommand, cwd=staging)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['npm', 'run', 'build', '--', '--girder-version=3.1.24', '--static-path=/usr/share/girder/static', '--static-public-path=/static', '--no-progress=false', '--env=prod']' returned non-zero exit status 3.

**Comment by manthey** [comment]
What version of node/npm are you using?  Until a refactor lands (soon, hopefully), girder currently requires node 14 to build the client.

**Comment by manthey** [comment]
Closing as Girder 5 should make this no longer applicable.
